Error messages -> Correct mobile first page to access to a web browser, displaying hangup button at the right button and refactoring appbar
openfun/jitsi-box pull request #22
Opened 2021-11-26 14:34 UTC by mogham

2021-11-26 14:47 UTC, Minosity-VR commented on box-ui/src/components/ts/JitsiComponent.tsx
> +                        SHOW_JITSI_WATERMARK: true,
C'est déjà la config de base non ? Tu voulais mettre `false` à la place ?

2021-11-26 14:49 UTC, Minosity-VR commented on box-ui/src/components/ts/JitsiComponent.tsx
> +                        startWithVideoMuted: true,
Pour l'audio je comprends pour éviter les larsen, mais la vidéo ça vaut le coup de la mute au début aussi ?

2021-11-26 14:50 UTC, ArthurNdy requested changes

2021-11-26 14:50 UTC, ArthurNdy commented on box-ui/src/components/ts/JitsiComponent.tsx
> +                        startWithVideoMuted: true,
je laisserais bien la video en false quand meme

2021-11-26 15:10 UTC, mkgharbi commented on box-ui/src/components/ts/JitsiComponent.tsx
> +                        SHOW_JITSI_WATERMARK: true,
Will be deleted

2021-11-29 08:55 UTC, Minosity-VR approved these changes

2021-11-29 09:52 UTC, ArthurNdy approved these changes

2021-11-29 09:52 UTC, Minosity-VR approved these changes

2021-11-29 09:52 UTC, merged