Image upload
openfun/jitsi-box pull request #59
Opened 2022-02-28 16:15 UTC by AladdinVR

Getting policy from fastAPI server (see clearboard project to see how the policy is managed) and uploading image to backend server relatively to this policy

2022-03-01 07:18 UTC, sampaccoud commented
@AladdinVR in your description you can use a link to the other project when you mention it

2022-03-02 14:19 UTC, AladdinVR commented
> @AladdinVR in your description you can use a link to the other project when you mention it

2022-03-07 09:20 UTC, djexvr requested changes

2022-03-07 09:20 UTC, djexvr commented on box-ui/src/components/ts/CameraDetectorComponent.tsx
> +const CameraDetector = (props: any) => {
You should add type for the props

2022-03-07 09:20 UTC, djexvr commented on box-ui/src/components/ts/CameraDetectorComponent.tsx
>          navigator.mediaDevices.enumerateDevices().then((devices: Array<any>) => {
You should use [existing types](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.mediadevices.html#enumeratedevices) for the devices

2022-03-07 09:20 UTC, djexvr commented on box-ui/src/components/ts/CaptureImageComponent.tsx
> +        console.log(props.camera['deviceId']);
You should remove console.log before merge

2022-03-07 09:20 UTC, djexvr commented on box-ui/src/components/ts/CaptureImageComponent.tsx
> +                const address = 'http://localhost:8070/policy';
You should create a .env for this kind of url as it won't work on other devices

2022-03-07 09:20 UTC, djexvr commented on box-ui/src/components/ts/CaptureImageComponent.tsx
> +import FormData from 'form-data';
Why do you need a package for FormData since it is in the [JS api](https://developer.mozilla.org/fr/docs/Web/API/FormData) ?

2022-03-07 14:03 UTC, merged